# Generated by Django 6.0.2 on 2026-05-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_task_assignee_task_assignees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
