# Generated by Django 6.0.2 on 2026-05-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_subtask_taskcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user_model',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user_model',
            name='profile_picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
