# Generated by Django 6.0.2 on 2026-06-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='can_crud_tasks',
            field=models.BooleanField(default=False),
        ),
    ]
