# Generated by Django 6.0.2 on 2026-06-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_notification_announcement_alter_notification_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', 'To-do'), ('IN_PROGRESS', 'In Progress'), ('HOLD', 'Hold'), ('IN_REVIEW', 'In Review'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='status',
            field=models.CharField(choices=[('PENDING', 'To-do'), ('IN_PROGRESS', 'In Progress'), ('HOLD', 'Hold'), ('IN_REVIEW', 'In Review'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='core_notifi_recipie_aeffaf_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='core_notifi_created_d0c445_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='core_task_status_e18e62_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority'], name='core_task_priorit_e802be_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='core_task_due_dat_d0a0d3_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_at'], name='core_task_created_9e4493_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['team_member'], name='core_timesh_team_me_10b1d1_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['task'], name='core_timesh_task_id_4c5abd_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['status'], name='core_timesh_status_85e466_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['start_time'], name='core_timesh_start_t_34da0b_idx'),
        ),
    ]
