# Generated by Django 6.0.2 on 2026-06-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_task_status_alter_timesheet_status_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project_name'], name='core_task_project_b43c8e_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_name'], name='core_task_task_na_6a8ac5_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['created_at'], name='core_timesh_created_38dc94_idx'),
        ),
    ]
