# Generated by Django 6.0.2 on 2026-06-15 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_task_core_task_project_b43c8e_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeScorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('task_completion_rate', models.FloatField(default=0.0)),
                ('working_hours', models.FloatField(default=0.0)),
                ('quality_score', models.FloatField(default=0.0)),
                ('attendance_score', models.FloatField(default=0.0)),
                ('overall_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20)),
                ('admin_comments', models.TextField(blank=True, default='')),
                ('superadmin_comments', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['employee', 'month'], name='core_employ_employe_afca1d_idx'), models.Index(fields=['status'], name='core_employ_status_9935fc_idx')],
                'unique_together': {('employee', 'month')},
            },
        ),
    ]
