# Generated by Django 6.0.2 on 2026-06-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0016_employeescorecard'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['audience'], name='core_announ_audienc_5d46b7_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['sender'], name='core_announ_sender__419416_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['created_at'], name='core_announ_created_6815a3_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'updated_at'], name='core_task_status_0e346c_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'due_date'], name='core_task_status_d09cc7_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['task'], name='core_taskco_task_id_7084f1_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['user'], name='core_taskco_user_id_cc3c51_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['created_at'], name='core_taskco_created_94f02f_idx'),
        ),
        migrations.AddIndex(
            model_name='user_model',
            index=models.Index(fields=['role'], name='core_user_m_role_7b70fb_idx'),
        ),
        migrations.AddIndex(
            model_name='user_model',
            index=models.Index(fields=['created_by'], name='core_user_m_created_cb05be_idx'),
        ),
    ]
