# Generated by Django 6.0.6 on 2026-07-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_announcement_core_announ_audienc_5d46b7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeescorecard',
            name='learning_rate_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='employeescorecard',
            name='timesheet_compliance',
            field=models.FloatField(default=0.0),
        ),
    ]
